### PR TITLE
Add more fields to oneDrive item

### PR DESCRIPTION
**Pull request by ti55987**
We are working on integrating microsoft OneDrive API.  This PR is to add more available fields in OneDriveItem 
Ref
https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0

Thanks !

### CODE REVIEW

**Comment by goh-chunlin** [comment]
This sounds great, but why do @ti55987 close this PR?

**Comment by ti55987** [comment]
> This sounds great, but why do @ti55987 close this PR?

thanks for the quick review! I don't intend  to change the  go mod path.  Will update it later !

**Comment by goh-chunlin** [comment]
> > This sounds great, but why do @ti55987 close this PR?
> 
> thanks for the quick review! I don't intend to change the go mod path. Will update it later !

Thank you! I shall wait for your new updates then. =)

Let me know if you need my help too.


Best regards,
Chun Lin

**Comment by goh-chunlin** [comment]
Modified and approved at #14

**Pull request closed without merging**
