### PR TITLE
Add item download to in-memory []byte

### PR DESCRIPTION
**Pull request by tonimelisma**

### CODE REVIEW

**Comment by tonimelisma** [comment]
Closes #17

**Comment by tonimelisma** [comment]
@goh-chunlin hey? Do you accept pull requests? Is this library still being maintained?

**Review by goh-chunlin — APPROVED** [review]
Thank you for the DownloadItem implementation, @tonimelisma

**Comment by goh-chunlin** [comment]
> @goh-chunlin hey? Do you accept pull requests? Is this library still being maintained?

Hi, @tonimelisma. Yes, we do accept PR. This library is still being maintained as well.

Thank you again for your contribution. =D

**Comment by prochac** [comment]
It is [my implementation](https://github.com/goh-chunlin/go-onedrive/issues/17#issuecomment-1197795393), but I take the thanks. You welcome.

But could you @goh-chunlin bump the version up? So we can finally stop using my fork.

**Comment by goh-chunlin** [comment]
> It is [my implementation](https://github.com/goh-chunlin/go-onedrive/issues/17#issuecomment-1197795393), but I take the thanks. You welcome.
> 
> But could you @goh-chunlin bump the version up? So we can finally stop using my fork.

Hi @prochac ,

I see, then I shall thank you once again for your contribution =D

The PR has been merged last year. Your changes [have been included](https://github.com/goh-chunlin/go-onedrive/blob/main/onedrive/driveitems.go), so it is safe to continue use the main branch here. 

Please correct me if I have misunderstood you.

Thank you again for your time in this project.

**Pull request merged**
